### PR TITLE
show tooltip if the cell content is taller than the cell height - fixes #740

### LINKED ISSUE #740: AutoTooltips not working for word-wrapped columns
When a column is word-wrapped, and its data goes past the bottom of the cell, tooltips do not work.  Tooltips should display when the data is taller than the cell height, but they currently only display when the data is wider than the cell width.

I've fixed the code, but not sure how to submit a pull request.  I've attached the fixed file.

[slick.autotooltips.js.zip](https://github.com/6pac/SlickGrid/files/11296654/slick.autotooltips.js.zip)

### PR DESCRIPTION
**Pull request by tr4npt**
The current code does not show a tooltip when word wrap is turned on and the text is taller than the cell height.

### CODE REVIEW

File: plugins/slick.autotooltips.js [hunk 1]
```diff
@@ -56,7 +56,9 @@
             if (options.maxToolTipLength && text.length > options.maxToolTipLength) {
               text = text.substr(0, options.maxToolTipLength - 3) + "...";
             }
-          } else {
+          } else if ($node.innerHeight() < $node[0].scrollHeight) {
```
Comment (ghiscoding) [inline plugins/slick.autotooltips.js:59]: why not merge this `else if` into the first `if`? I think this would be better and it would also include the line 56-58 for longer text tooltip

Comment (tr4npt) [reply plugins/slick.autotooltips.js]: That is a good suggestion!  I've updated the code.  Thanks!

**Comment by ghiscoding** [comment]
@tr4npt for completeness and our understanding could you please provide a print screen of what this resolves? Thank you

**Comment by tr4npt** [comment]
Here is an image demonstrating the autotooltip functionality when the text is taller than the cell contents.  Before this fix, the tooltip would not appear.
autotooltips_fix
