### PR TITLE
Feat: shadow dom, fixes issue #889

### LINKED ISSUE #889: using a global CSS in the <head> is not compatible with shadow DOM
SlickGrid currently generates a dynamic CSS stylesheet and appends it to the <head> of the document. I have been using Lit Elements, which is a library that uses Shadow DOM. When my slickgrid container element is inside a shadow DOM tree, the global stylesheet from the <head> does not affect it (which is how the shadow DOM works by design). 

It would be great if slickgrid could handle these global styles in a way that the work when the container element is inside a shadow DOM tree. I've referenced below the method which generates the global stylesheet (to the best of my knowledge after reading the source code):

https://github.com/6pac/SlickGrid/blob/7deb1707c267052cefb64da3166047e5761aa6f2/src/slick.grid.ts#L2301-L2325

### PR DESCRIPTION
**Pull request by megatron0000**
- Adds an option to Slick.Grid to make it work when inside a shadow DOM tree. It did not work because the shadow DOM is not affected by external stylesheets, so to fix this we have to add dynamic stylesheets directly inside the shadow DOM.
- fixes #889

### CODE REVIEW

**Comment by megatron0000** [comment]
Does the new example make sense where it is ? (i.e. next to the basic example). If there are problems in this proposed solution, I'd be happy to review

File: src/models/gridOption.interface.ts [hunk 1]
```diff
@@ -269,6 +269,9 @@ export interface GridOption<C extends BaseColumn = BaseColumn> {
   /** Defaults to true, which leads to render a separate span for the number and styles it with css class <i>slick-sort-indicator-numbered</i> */
   sortColNumberInSeparateSpan?: boolean;
 
+  /** Defaults to undefined. If we are inside a shadow DOM tree, this must be the shadow root of the tree */
+  shadowRoot?: ShadowRoot | undefined;
```
Comment (ghiscoding) [inline src/models/gridOption.interface.ts:273]: you can remove the `| undefined` since `?.` already covers that

**Review by ghiscoding — CHANGES_REQUESTED** [review]

**Comment by ghiscoding** [comment]
looking good, we can add it to the list of Examples in the Examples Wiki after it gets merged

File: src/models/gridOption.interface.ts (hunk 1 above)
Comment (megatron0000) [reply src/models/gridOption.interface.ts]: oh true, done

**Review by ghiscoding — APPROVED** [review]

**Comment by ghiscoding** [comment]
@megatron0000 thanks for the contribution, this is now available in today's release [v5.4.0](https://github.com/6pac/SlickGrid/releases). 

BTW, I'm not sure all controls/plugins will all work properly because of some body selector and event listeners. I never use ShadowDOM so if you find some issues please contribute again 😉
